[build]
  node_version = "20" # Recommended for Netlify Functions, ensures modern JS features
  functions = "netlify/functions"
  publish = "."
  base = "/"

[functions]
  directory = "netlify/functions"